---

# Audit Delete


# STS Role Assume
- name:                STS Role Assume
  sts_assume_role:
    aws_access_key:    "{{ aws_access_key }}"
    aws_secret_key:    "{{ aws_secret_key }}"
    role_arn:          "{{ aws_iam_role_sts_arn }}"
    role_session_name: "{{ aws_iam_role_sts_name }}"
  register:            this_assumed_role


# Audit CloudTrail Delete
- name:       Audit CloudTrail Delete
  cloudtrail:
    name:     "trail-{{ audit_s3_bucket_name }}"
    aws_access_key: "{{ this_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ this_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ this_assumed_role.sts_creds.session_token }}"
    state:    "absent"


# Audit S3 Lifecycle Logs Delete
# - name: 
#   s3_lifecycle:
#     name:       "{{ audit_s3_bucket_name }}"
#     prefix:     "{{ audit_s3_target_bucket_log_prefix }}"
#     status:     "disabled"
#     state:      "present"
    

# Audit S3 Logs Delete
# - name:         Audit S3 Logs Delete
#   s3_lifecycle:
#     name:       "{{ audit_s3_bucket_name }}"
#     prefix:     "{{ audit_s3_target_bucket_log_prefix }}"
#     state:      "absent"


# Audit S3 Bucket Delete
- name:      Audit S3 Bucket Delete
  s3_bucket:
    name:    "{{ audit_s3_bucket_name }}"
    aws_access_key: "{{ this_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ this_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ this_assumed_role.sts_creds.session_token }}"
    state:   "absent"
    force:   "yes"


...