---

# STS Role Assume
- name:                STS Role Assume
  sts_assume_role:
    aws_access_key:    "{{ aws_access_key }}"
    aws_secret_key:    "{{ aws_secret_key }}"
    role_arn:          "{{ aws_iam_role_sts_arn }}"
    role_session_name: "{{ aws_iam_role_sts_name }}"
  register:            this_assumed_role


# VPC Create
- name:             VPC Create
  ec2_vpc_net:
    name:           "{{ vpc_name }}"
    cidr_block:     "{{ vpc_cidr_block }}"
    region:         "{{ aws_region_code }}"
    aws_access_key: "{{ this_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ this_assumed_role.sts_creds.secret_key }}"
    security_token: "{{ this_assumed_role.sts_creds.session_token }}"
    state:          "present"
  register:         this_vpc


...